#!/bin/bash

mv /usr/bin/google_speech-multilanguage /usr/local/bin/google_speech-multilanguage

update-alternatives --install /etc/alternatives/tts.gz tts "/usr/local/bin/google_speech-multilanguage" 20
update-alternatives --install /etc/alternatives/tts.gz tts "/usr/bin/espeak-ng-multilanguage" 15
update-alternatives --remove tts /usr/bin/espeak 
update-alternatives --remove tts /usr/bin/espeak_fr
update-alternatives --remove tts /usr/local/bin/google_speech
update-alternatives --remove tts /usr/local/bin/google_speech_fr

pip3 install google_speech
